# This is a sample build configuration for Java (Maven).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: maven:latest
pipelines:
  custom:
    selenium-test:
     - step:
         script:
           - whoami
           - wget -N https://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip -P ~/
           - unzip ~/chromedriver_linux64.zip -d ~/
           - rm ~/chromedriver_linux64.zip
           - mv -f ~/chromedriver /usr/local/bin/chromedriver
           - chown root:root /usr/local/bin/chromedriver
           - chmod 0755 /usr/local/bin/chromedriver
           - mvn test